services:
  db:
    image: postgres:16-alpine
    container_name: ethid-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ethid}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-ethid}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks: [ backend ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m src.app.runner
    env_file:
      - .env
    environment:
      # Если в .env не задано, возьмём дефолт на docker-сетку:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/ethid}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks: [backend]

volumes:
  pg_data:

networks:
  backend:
    driver: bridge